# -*- coding: utf-8 -*-
"""TASK 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bl0vzpQDmdurvvCV3vGjBKeSqfu48f3o

1. Write a Python program to find those numbers which are divisible by 7 and multiple of 11, between 11000 and 2000 (both included).
"""

print ("numbers divisible by 7 and multiple of 11 are:")
for x in range  (1000,2000):
  if (x%7==0 and x%11==0):
    print(x)

"""2. Write a program to print this pattern

           #
          ## 
         ###
"""

n=int(input("Enter the number of rows:"))
k = 2*n - 2
for i in range(0, n):
  for j in range(0, k):
    print(end=" ")
  k = k - 2
  for j in range(0, i+1):
    print("# ", end="")
  print("\r")

"""3. list=[apple, orange, apple, banana]
. Replace all the apple in the list with grapes using for loop
"""

print("initial list")
fruits=['apple','orange','apple','banana']
print(fruits)
for x in range (0,4):
    if (fruits[x]=='apple'):
        fruits[x]='grape'
print("after changing 'apple' to 'grape'")
print(fruits)