# -*- coding: utf-8 -*-
"""TASK 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WYYJUauOMgjQkhSjYIgJDlqcLbp5zZdR

1. Generate a 3 x 3 matrix using random module.
"""

import numpy as np
x = np.random.random((3,3))
print(x)

"""2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.
"""

import numpy as np
x=np.array([(1,2,3,4),(5,6,7,8),(8,7,6,5),(4,3,2,1)])
y=np.array([(1,2,3,4),(5,6,7,8),(8,7,6,5),(4,3,2,1)])
print(x)
print()
print(y)
print()
x1=x.reshape(2,8)
y1=y.reshape(2,8)
print("after reshaping")
print()
print(x1)
print()
print(y1)

np.vstack((x1,y1))

np.hstack((x1,y1))