# -*- coding: utf-8 -*-
"""TASK 12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmQHCssWixSDfPNnI2dAJ4O-OqFjiGcf

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.
"""

import numpy as np

mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)

print("Trace of the Array is: \n",mat.trace())

"""2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix."""

import numpy as np
mat = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matix\n",mat)
print("\nThe Inverse of Matrix is :\n",np.linalg.inv(mat))

"""3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array."""

import numpy as np

mat = np.random.randint(0,8,(3,3))
print("Array\n",mat)
print("\nThe Norm of the Matrix is\n",np.linalg.norm(mat))

"""4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array."""

import numpy as np

mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("\nThe EigenValue and EigenVectors of the Matrix is\n",np.linalg.eig(mat))