# -*- coding: utf-8 -*-
"""TASK 11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9ezAY6M_4e3APb08XzMmDEvsmGL-88k

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).
"""

import numpy as np

mat1 = np.random.randint(0,8,(3,3))
mat2 = np.random.randint(10,19,(3,3))

print("Matrix A\n" ,mat1)

print("\nMatrix B\n" ,mat2)

out = np.multiply.outer(mat1,mat2)
print("Outer Products\n",out)

dot = np.dot(mat1,mat2)
print("Dot Products\n",dot)

Ele = np.multiply(mat1,mat2)
print("Element Wise\n",Ele)

"""2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)"""

import numpy as np

mat = np.random.randint(0,16,(4,4))
print("Matrix is \n", mat)

#adding 4(scalar) to the matrix
scal = 2
addScal = mat + scal
print("\n Scalar Matrix\n",addScal)

#matrix broadcasting
nums = np.array([1,2,3,4])
mult = mat * nums
print("\nThe Multiplication by broadcasting\n",mult)