# -*- coding: utf-8 -*-
"""TASK 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vw2S8gKUv2YPPhdFsz21LILU2h87DAU7

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.
"""

import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)

sum = np.sum(mat)
print("\n Sum is :\n",sum)

"""2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array."""

import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)

col = np.sum(mat,axis =0)
print("\n Sum of Columns:\n",col)

row = np.sum(mat,axis =1)
print("\n Sum of Columns:\n",row)

"""3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.
"""

import numpy as np
mat = np.random.randint(0,15,(4,4))
print("\n The Matrix is:\n",mat)

min = np.min(mat)
print("\n Minimum Value is\n",min)

max = np.max(mat)
print("\n Maximum Value is\n",max)

mean = np.mean(mat)
print("\n Minimum Value is\n",mean)

"""4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.
"""

import numpy as np
mat = np.random.randint(0,99,(10,10))
print("\n The Matrix is:\n",mat)

print("\nThe 7th row is :\n",mat[7,:])

print("\nThe 4-8th row is :\n",mat[4:8,:])

print("\nThe value at (5,5) is :\n",mat[5,5])

print("\nThe 5th column) is :\n",mat[:,5])

print("\nThe 2-5th column) is :\n",mat[:,2:5])